package com.rosaloves.net.shorturl.bitly.url;

import java.net.URL;

/**
 * A BitlyUrl is a URL shortend by the bit.ly service.
 *
 * TODO undocumented member shortKeywordUrl
 *
 * $Id$
 *
 * @author Chris Lewis (Feb 24, 2009)
 */
public interface BitlyUrl {
	
	/**
	 * Get the hash generated by bit.ly to identify the URL.
	 * 
	 * @return The URL hash, as assigned by bit.ly.
	 */
	public String getHash();
	
	/**
	 * Get the user-defined hash.
	 * 
	 * @return The user-defined hash.
	 */
	public String getUserHash();
	
	/**
	 * Get the generated shortened URL.
	 * 
	 * @return The shortend URL.
	 */
	public URL getShortUrl();
	
	/**
	 * Get the orignal long URL.
	 * 
	 * @return The URL to which this object points.
	 */
	public URL getLongUrl();
	
}